name: Build module against Playerbot Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04.3

    steps:
    - name: Checkout this module
      uses: actions/checkout@v4
      with:
        path: module-src
        fetch-depth: 1

    - name: Checkout AzerothCore (Playerbot branch)
      uses: actions/checkout@v4
      with:
        repository: mod-playerbots/azerothcore-wotlk
        ref: Playerbot
        path: azerothcore
        fetch-depth: 1

    - name: Copy module into AzerothCore/modules
      run: |
        mkdir -p azerothcore/modules
        cp -r module-src azerothcore/modules/mod-guild-village

    - name: Install build deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang \
          libmysqlclient-dev \
          libssl-dev \
          libreadline-dev \
          zlib1g-dev \
          libbz2-dev \
          libncurses-dev \
          libboost-all-dev \
          git

    - name: Configure CMake
      working-directory: azerothcore
      run: |
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
          -DTOOLS=ON \
          -DSCRIPTS=static \
          -DWITH_PLAYERBOTS=1 \
          -DWITH_WARNINGS=1

    - name: Build worldserver & authserver
      working-directory: azerothcore/build
      run: |
        make -j"$(nproc)" worldserver authserver

    - name: Show worldserver version
      working-directory: azerothcore/build/bin
      run: |
        ./worldserver --version || true
